export interface Food {
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  category: string;
  subCategory: string;
  restaurant: string;
}

export const foods: Food[] = [
  {
    name: "Big Mac",
    calories: 550,
    protein: 25,
    carbs: 46,
    fat: 30,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "McDonald's",
  },
  {
    name: "Quarter Pounder with Cheese",
    calories: 520,
    protein: 29,
    carbs: 40,
    fat: 25,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "McDonald's",
  },
  {
    name: "Chicken McNuggets (10 pc)",
    calories: 410,
    protein: 23,
    carbs: 22,
    fat: 24,
    category: "Chicken",
    subCategory: "Nuggets",
    restaurant: "McDonald's",
  },
  {
    name: "McFlurry with M&M's",
    calories: 640,
    protein: 13,
    carbs: 85,
    fat: 28,
    category: "Dessert",
    subCategory: "Frozen",
    restaurant: "McDonald's",
  },
  {
    name: "Whopper",
    calories: 657,
    protein: 28,
    carbs: 49,
    fat: 39,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "Burger King",
  },
  {
    name: "Chicken Fries",
    calories: 280,
    protein: 13,
    carbs: 25,
    fat: 14,
    category: "Chicken",
    subCategory: "Fry",
    restaurant: "Burger King",
  },
  {
    name: "Chalupa Supreme (Beef)",
    calories: 350,
    protein: 12,
    carbs: 35,
    fat: 18,
    category: "Taco",
    subCategory: "Beef",
    restaurant: "Taco Bell",
  },
  {
    name: "Crunchwrap Supreme",
    calories: 530,
    protein: 16,
    carbs: 55,
    fat: 27,
    category: "Wrap",
    subCategory: "Beef",
    restaurant: "Taco Bell",
  },
  {
    name: "Nachos BellGrande",
    calories: 740,
    protein: 16,
    carbs: 78,
    fat: 41,
    category: "Sides",
    subCategory: "Chips",
    restaurant: "Taco Bell",
  },
  {
    name: "Chicken Burrito Bowl",
    calories: 470,
    protein: 41,
    carbs: 45,
    fat: 14,
    category: "Bowl",
    subCategory: "Chicken",
    restaurant: "Chipotle",
  },
  {
    name: "Steak Burrito",
    calories: 820,
    protein: 48,
    carbs: 70,
    fat: 38,
    category: "Burrito",
    subCategory: "Beef",
    restaurant: "Chipotle",
  },
  {
    name: "Chips & Guacamole",
    calories: 770,
    protein: 9,
    carbs: 70,
    fat: 50,
    category: "Sides",
    subCategory: "Chips",
    restaurant: "Chipotle",
  },
  {
    name: "Famous Bowl",
    calories: 710,
    protein: 25,
    carbs: 75,
    fat: 35,
    category: "Bowl",
    subCategory: "Mixed",
    restaurant: "KFC",
  },
  {
    name: "Original Recipe Chicken (2 pc)",
    calories: 510,
    protein: 36,
    carbs: 20,
    fat: 31,
    category: "Chicken",
    subCategory: "Fried",
    restaurant: "KFC",
  },
  {
    name: "Chicken Sandwich",
    calories: 440,
    protein: 28,
    carbs: 41,
    fat: 19,
    category: "Sandwich",
    subCategory: "Chicken",
    restaurant: "Chick-fil-A",
  },
  {
    name: "Waffle Potato Fries (Medium)",
    calories: 420,
    protein: 5,
    carbs: 58,
    fat: 19,
    category: "Sides",
    subCategory: "Fry",
    restaurant: "Chick-fil-A",
  },
  {
    name: "Spicy Chicken Sandwich",
    calories: 450,
    protein: 28,
    carbs: 40,
    fat: 19,
    category: "Sandwich",
    subCategory: "Chicken",
    restaurant: "Popeyes",
  },
  {
    name: "Cajun Fries (Regular)",
    calories: 260,
    protein: 4,
    carbs: 34,
    fat: 12,
    category: "Sides",
    subCategory: "Fry",
    restaurant: "Popeyes",
  },
  {
    name: "Dave's Single",
    calories: 570,
    protein: 29,
    carbs: 41,
    fat: 30,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "Wendy's",
  },
  {
    name: "Baconator",
    calories: 950,
    protein: 57,
    carbs: 40,
    fat: 63,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "Wendy's",
  },
  {
    name: "Frosty (Medium)",
    calories: 470,
    protein: 13,
    carbs: 62,
    fat: 16,
    category: "Dessert",
    subCategory: "Frozen",
    restaurant: "Wendy's",
  },
  {
    name: "Italian B.M.T. Footlong",
    calories: 820,
    protein: 36,
    carbs: 106,
    fat: 28,
    category: "Sandwich",
    subCategory: "Cold Cut",
    restaurant: "Subway",
  },
  {
    name: 'Turkey Breast 6"',
    calories: 280,
    protein: 18,
    carbs: 34,
    fat: 8,
    category: "Sandwich",
    subCategory: "Turkey",
    restaurant: "Subway",
  },
  {
    name: "Pepperoni Pizza (Large slice)",
    calories: 320,
    protein: 14,
    carbs: 34,
    fat: 15,
    category: "Pizza",
    subCategory: "Pepperoni",
    restaurant: "Domino's",
  },
  {
    name: "Cheesy Bread",
    calories: 140,
    protein: 6,
    carbs: 16,
    fat: 6,
    category: "Sides",
    subCategory: "Bread",
    restaurant: "Domino's",
  },
  {
    name: "Pepperoni Pizza (slice)",
    calories: 300,
    protein: 13,
    carbs: 32,
    fat: 13,
    category: "Pizza",
    subCategory: "Pepperoni",
    restaurant: "Pizza Hut",
  },
  {
    name: "Meat Lovers Pizza (slice)",
    calories: 380,
    protein: 17,
    carbs: 35,
    fat: 19,
    category: "Pizza",
    subCategory: "Meat",
    restaurant: "Pizza Hut",
  },
  {
    name: "Orange Chicken",
    calories: 490,
    protein: 25,
    carbs: 55,
    fat: 18,
    category: "Entree",
    subCategory: "Chicken",
    restaurant: "Panda Express",
  },
  {
    name: "Beijing Beef",
    calories: 470,
    protein: 13,
    carbs: 45,
    fat: 27,
    category: "Entree",
    subCategory: "Beef",
    restaurant: "Panda Express",
  },
  {
    name: "Fried Rice",
    calories: 520,
    protein: 11,
    carbs: 78,
    fat: 18,
    category: "Sides",
    subCategory: "Rice",
    restaurant: "Panda Express",
  },
  {
    name: "Double-Double",
    calories: 670,
    protein: 37,
    carbs: 43,
    fat: 39,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "In-N-Out",
  },
  {
    name: "Animal Style Fries",
    calories: 750,
    protein: 18,
    carbs: 92,
    fat: 35,
    category: "Sides",
    subCategory: "Fry",
    restaurant: "In-N-Out",
  },
  {
    name: "Burrito Supreme",
    calories: 390,
    protein: 15,
    carbs: 45,
    fat: 16,
    category: "Burrito",
    subCategory: "Beef",
    restaurant: "Taco Bell",
  },
  {
    name: "Egg McMuffin",
    calories: 310,
    protein: 17,
    carbs: 30,
    fat: 14,
    category: "Breakfast",
    subCategory: "Egg",
    restaurant: "McDonald's",
  },
  {
    name: "Grilled Chicken Sandwich",
    calories: 380,
    protein: 37,
    carbs: 29,
    fat: 13,
    category: "Sandwich",
    subCategory: "Chicken",
    restaurant: "McDonald's",
  },
  {
    name: "Cinnamon Twists",
    calories: 170,
    protein: 2,
    carbs: 24,
    fat: 6,
    category: "Dessert",
    subCategory: "Pastry",
    restaurant: "Taco Bell",
  },
  {
    name: "Quesarito",
    calories: 650,
    protein: 22,
    carbs: 70,
    fat: 32,
    category: "Burrito",
    subCategory: "Beef",
    restaurant: "Taco Bell",
  },
  {
    name: "Chicken Caesar Salad",
    calories: 470,
    protein: 40,
    carbs: 22,
    fat: 31,
    category: "Salad",
    subCategory: "Chicken",
    restaurant: "Chipotle",
  },
  {
    name: "Cookies (3 pack)",
    calories: 210,
    protein: 2,
    carbs: 26,
    fat: 10,
    category: "Dessert",
    subCategory: "Baked",
    restaurant: "Subway",
  },
  {
    name: "Honey Mustard BBQ Tender Wrap",
    calories: 350,
    protein: 14,
    carbs: 41,
    fat: 14,
    category: "Wrap",
    subCategory: "Chicken",
    restaurant: "KFC",
  },
  {
    name: "McChicken Meal (with Med Fries)",
    calories: 720,
    protein: 19,
    carbs: 84,
    fat: 33,
    category: "Combo",
    subCategory: "Chicken",
    restaurant: "McDonald's",
  },
  {
    name: "Filet-O-Fish",
    calories: 390,
    protein: 16,
    carbs: 39,
    fat: 18,
    category: "Sandwich",
    subCategory: "Fish",
    restaurant: "McDonald's",
  },
  {
    name: "Sausage McMuffin with Egg Meal",
    calories: 800,
    protein: 22,
    carbs: 78,
    fat: 45,
    category: "Combo",
    subCategory: "Sausage",
    restaurant: "McDonald's",
  },
  {
    name: "Double Quarter Pounder with Cheese",
    calories: 740,
    protein: 48,
    carbs: 41,
    fat: 41,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "McDonald's",
  },
  {
    name: "Whopper Meal (with Med Fries)",
    calories: 1040,
    protein: 33,
    carbs: 92,
    fat: 42,
    category: "Combo",
    subCategory: "Beef",
    restaurant: "Burger King",
  },
  {
    name: "Original Chicken Sandwich",
    calories: 660,
    protein: 26,
    carbs: 60,
    fat: 31,
    category: "Sandwich",
    subCategory: "Chicken",
    restaurant: "Burger King",
  },
  {
    name: "Double Whopper",
    calories: 900,
    protein: 48,
    carbs: 58,
    fat: 53,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "Burger King",
  },
  {
    name: "Bacon King",
    calories: 1150,
    protein: 61,
    carbs: 65,
    fat: 69,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "Burger King",
  },
  {
    name: "Crunchwrap Supreme Combo",
    calories: 920,
    protein: 21,
    carbs: 90,
    fat: 39,
    category: "Combo",
    subCategory: "Beef",
    restaurant: "Taco Bell",
  },
  {
    name: "3 Crunchy Tacos Combo",
    calories: 510,
    protein: 24,
    carbs: 45,
    fat: 27,
    category: "Combo",
    subCategory: "Beef",
    restaurant: "Taco Bell",
  },
  {
    name: "Quesadilla (Chicken)",
    calories: 510,
    protein: 26,
    carbs: 45,
    fat: 24,
    category: "Quesadilla",
    subCategory: "Chicken",
    restaurant: "Taco Bell",
  },
  {
    name: "Cheesy Gordita Crunch",
    calories: 490,
    protein: 20,
    carbs: 54,
    fat: 22,
    category: "Taco",
    subCategory: "Beef",
    restaurant: "Taco Bell",
  },
  {
    name: "Steak Burrito Bowl Combo",
    calories: 1100,
    protein: 52,
    carbs: 100,
    fat: 55,
    category: "Combo",
    subCategory: "Beef",
    restaurant: "Chipotle",
  },
  {
    name: "Carnitas Burrito",
    calories: 850,
    protein: 42,
    carbs: 85,
    fat: 38,
    category: "Burrito",
    subCategory: "Pork",
    restaurant: "Chipotle",
  },
  {
    name: "Barbacoa Tacos (3 pc)",
    calories: 540,
    protein: 34,
    carbs: 50,
    fat: 22,
    category: "Taco",
    subCategory: "Beef",
    restaurant: "Chipotle",
  },
  {
    name: "3 pc Chicken Box (with Fries & Biscuit)",
    calories: 1010,
    protein: 51,
    carbs: 100,
    fat: 47,
    category: "Combo",
    subCategory: "Chicken",
    restaurant: "KFC",
  },
  {
    name: "Zinger Burger",
    calories: 540,
    protein: 30,
    carbs: 45,
    fat: 25,
    category: "Sandwich",
    subCategory: "Chicken",
    restaurant: "KFC",
  },
  {
    name: "Popcorn Chicken Combo",
    calories: 940,
    protein: 33,
    carbs: 80,
    fat: 35,
    category: "Combo",
    subCategory: "Chicken",
    restaurant: "KFC",
  },
  {
    name: "Twister Wrap",
    calories: 550,
    protein: 23,
    carbs: 55,
    fat: 24,
    category: "Wrap",
    subCategory: "Chicken",
    restaurant: "KFC",
  },
  {
    name: "Spicy Chicken Sandwich Combo",
    calories: 870,
    protein: 33,
    carbs: 70,
    fat: 33,
    category: "Combo",
    subCategory: "Chicken",
    restaurant: "Chick-fil-A",
  },
  {
    name: "8 pc Nuggets Combo",
    calories: 670,
    protein: 33,
    carbs: 65,
    fat: 28,
    category: "Combo",
    subCategory: "Chicken",
    restaurant: "Chick-fil-A",
  },
  {
    name: "Cobb Salad with Grilled Chicken",
    calories: 420,
    protein: 40,
    carbs: 14,
    fat: 22,
    category: "Salad",
    subCategory: "Chicken",
    restaurant: "Chick-fil-A",
  },
  {
    name: "3 pc Chicken Tenders Combo",
    calories: 890,
    protein: 38,
    carbs: 85,
    fat: 44,
    category: "Combo",
    subCategory: "Chicken",
    restaurant: "Popeyes",
  },
  {
    name: "Baconator Combo (with Med Fries)",
    calories: 1370,
    protein: 62,
    carbs: 82,
    fat: 53,
    category: "Combo",
    subCategory: "Beef",
    restaurant: "Wendy's",
  },
  {
    name: "Dave's Single Combo",
    calories: 990,
    protein: 34,
    carbs: 95,
    fat: 55,
    category: "Combo",
    subCategory: "Beef",
    restaurant: "Wendy's",
  },
  {
    name: "Spicy Chicken Sandwich",
    calories: 500,
    protein: 28,
    carbs: 46,
    fat: 22,
    category: "Sandwich",
    subCategory: "Chicken",
    restaurant: "Wendy's",
  },
  {
    name: "10 pc Chicken Nuggets",
    calories: 420,
    protein: 20,
    carbs: 38,
    fat: 20,
    category: "Chicken",
    subCategory: "Nuggets",
    restaurant: "Wendy's",
  },
  {
    name: "Sweet Onion Chicken Teriyaki Footlong",
    calories: 740,
    protein: 50,
    carbs: 74,
    fat: 28,
    category: "Sandwich",
    subCategory: "Chicken",
    restaurant: "Subway",
  },
  {
    name: "Steak & Cheese Footlong",
    calories: 760,
    protein: 52,
    carbs: 72,
    fat: 26,
    category: "Sandwich",
    subCategory: "Beef",
    restaurant: "Subway",
  },
  {
    name: "Meatball Marinara 6\"",
    calories: 430,
    protein: 20,
    carbs: 44,
    fat: 18,
    category: "Sandwich",
    subCategory: "Beef",
    restaurant: "Subway",
  },
  {
    name: "ExtravaganZZa Pizza (Large slice)",
    calories: 380,
    protein: 16,
    carbs: 42,
    fat: 17,
    category: "Pizza",
    subCategory: "Meat",
    restaurant: "Domino's",
  },
  {
    name: "Classic Chicken Alfredo Pasta",
    calories: 660,
    protein: 29,
    carbs: 60,
    fat: 32,
    category: "Entree",
    subCategory: "Pasta",
    restaurant: "Domino's",
  },
  {
    name: "Stuffed Crust Pepperoni Pizza (slice)",
    calories: 410,
    protein: 19,
    carbs: 39,
    fat: 21,
    category: "Pizza",
    subCategory: "Pepperoni",
    restaurant: "Pizza Hut",
  },
  {
    name: "Bigger Plate (2 Entrees + 1 Side)",
    calories: 1250,
    protein: 48,
    carbs: 98,
    fat: 45,
    category: "Combo",
    subCategory: "Mixed",
    restaurant: "Panda Express",
  },
  {
    name: "Mushroom Chicken",
    calories: 220,
    protein: 13,
    carbs: 10,
    fat: 8,
    category: "Entree",
    subCategory: "Chicken",
    restaurant: "Panda Express",
  },
  {
    name: "Broccoli Beef",
    calories: 150,
    protein: 9,
    carbs: 15,
    fat: 6,
    category: "Entree",
    subCategory: "Beef",
    restaurant: "Panda Express",
  },
  {
    name: "Double-Double Combo (with Fries)",
    calories: 1060,
    protein: 42,
    carbs: 82,
    fat: 62,
    category: "Combo",
    subCategory: "Beef",
    restaurant: "In-N-Out",
  },
  {
    name: "Hamburger",
    calories: 390,
    protein: 16,
    carbs: 40,
    fat: 19,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "In-N-Out",
  },
  {
    name: "Beltsander Wrap",
    calories: 520,
    protein: 26,
    carbs: 50,
    fat: 22,
    category: "Wrap",
    subCategory: "Chicken",
    restaurant: "Tim Hortons",
  },
  {
    name: "Chili with Toast",
    calories: 430,
    protein: 19,
    carbs: 46,
    fat: 18,
    category: "Entree",
    subCategory: "Beef",
    restaurant: "Tim Hortons",
  },
  {
    name: "Iced Capp (Medium)",
    calories: 360,
    protein: 3,
    carbs: 54,
    fat: 14,
    category: "Drink",
    subCategory: "Coffee",
    restaurant: "Tim Hortons",
  },
  {
    name: "Mozza Burger",
    calories: 560,
    protein: 29,
    carbs: 42,
    fat: 30,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "A&W",
  },
  {
    name: "Papa Burger Combo (with Fries)",
    calories: 1020,
    protein: 35,
    carbs: 95,
    fat: 55,
    category: "Combo",
    subCategory: "Beef",
    restaurant: "A&W",
  },
  {
    name: "Sweet Potato Fries",
    calories: 380,
    protein: 3,
    carbs: 55,
    fat: 15,
    category: "Sides",
    subCategory: "Fry",
    restaurant: "A&W",
  },
  {
    name: "ShackBurger",
    calories: 530,
    protein: 30,
    carbs: 38,
    fat: 28,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "Shake Shack",
  },
  {
    name: "SmokeShack Double",
    calories: 870,
    protein: 53,
    carbs: 50,
    fat: 56,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "Shake Shack",
  },
  {
    name: "Cheese Fries",
    calories: 560,
    protein: 12,
    carbs: 58,
    fat: 28,
    category: "Sides",
    subCategory: "Fry",
    restaurant: "Shake Shack",
  },
  {
    name: "Little Bacon Cheeseburger",
    calories: 730,
    protein: 32,
    carbs: 50,
    fat: 42,
    category: "Burger",
    subCategory: "Beef",
    restaurant: "Five Guys",
  },
  {
    name: "Fries (Little size)",
    calories: 530,
    protein: 8,
    carbs: 68,
    fat: 24,
    category: "Sides",
    subCategory: "Fry",
    restaurant: "Five Guys",
  },
  {
    name: "Classic Beef Patty",
    calories: 340,
    protein: 11,
    carbs: 12,
    fat: 27,
    category: "Bakery",
    subCategory: "Patty",
    restaurant: "Dairy Queen",
  },
];

export function pickRandomFood(): Food {
  return foods[Math.floor(Math.random() * foods.length)];
}

export function pickDailyFood(): Food {
  // Get today's date as YYYY-MM-DD
  const today = new Date().toISOString().split("T")[0];
  // Convert date string to a number for seeding
  const seed = today.split("-").reduce((acc, part) => acc + parseInt(part), 0);
  // Use modulo to get a consistent index for today
  const index = seed % foods.length;
  return foods[index];
}
