export interface Food {
  name: string;
  calories: number;
  protein: number;
  category: string;
  restaurant: string;
}

export const foods: Food[] = [
  {
    name: "Big Mac",
    calories: 550,
    protein: 25,
    category: "Burger",
    restaurant: "McDonald's",
  },
  {
    name: "Quarter Pounder with Cheese",
    calories: 520,
    protein: 29,
    category: "Burger",
    restaurant: "McDonald's",
  },
  {
    name: "Chicken McNuggets (10 pc)",
    calories: 410,
    protein: 23,
    category: "Chicken",
    restaurant: "McDonald's",
  },
  {
    name: "McFlurry with M&M's",
    calories: 640,
    protein: 13,
    category: "Dessert",
    restaurant: "McDonald's",
  },
  {
    name: "Whopper",
    calories: 657,
    protein: 28,
    category: "Burger",
    restaurant: "Burger King",
  },
  {
    name: "Chicken Fries",
    calories: 280,
    protein: 13,
    category: "Chicken",
    restaurant: "Burger King",
  },
  {
    name: "Chalupa Supreme (Beef)",
    calories: 350,
    protein: 12,
    category: "Taco",
    restaurant: "Taco Bell",
  },
  {
    name: "Crunchwrap Supreme",
    calories: 530,
    protein: 16,
    category: "Wrap",
    restaurant: "Taco Bell",
  },
  {
    name: "Nachos BellGrande",
    calories: 740,
    protein: 16,
    category: "Sides",
    restaurant: "Taco Bell",
  },
  {
    name: "Chicken Burrito Bowl",
    calories: 470,
    protein: 41,
    category: "Bowl",
    restaurant: "Chipotle",
  },
  {
    name: "Steak Burrito",
    calories: 820,
    protein: 48,
    category: "Burrito",
    restaurant: "Chipotle",
  },
  {
    name: "Chips & Guacamole",
    calories: 770,
    protein: 9,
    category: "Sides",
    restaurant: "Chipotle",
  },
  {
    name: "Famous Bowl",
    calories: 710,
    protein: 25,
    category: "Bowl",
    restaurant: "KFC",
  },
  {
    name: "Original Recipe Chicken (2 pc)",
    calories: 510,
    protein: 36,
    category: "Chicken",
    restaurant: "KFC",
  },
  {
    name: "Chicken Sandwich",
    calories: 440,
    protein: 28,
    category: "Sandwich",
    restaurant: "Chick-fil-A",
  },
  {
    name: "Waffle Potato Fries (Medium)",
    calories: 420,
    protein: 5,
    category: "Sides",
    restaurant: "Chick-fil-A",
  },
  {
    name: "Spicy Chicken Sandwich",
    calories: 450,
    protein: 28,
    category: "Sandwich",
    restaurant: "Popeyes",
  },
  {
    name: "Cajun Fries (Regular)",
    calories: 260,
    protein: 4,
    category: "Sides",
    restaurant: "Popeyes",
  },
  {
    name: "Dave's Single",
    calories: 570,
    protein: 29,
    category: "Burger",
    restaurant: "Wendy's",
  },
  {
    name: "Baconator",
    calories: 950,
    protein: 57,
    category: "Burger",
    restaurant: "Wendy's",
  },
  {
    name: "Frosty (Medium)",
    calories: 470,
    protein: 13,
    category: "Dessert",
    restaurant: "Wendy's",
  },
  {
    name: "Italian B.M.T. Footlong",
    calories: 820,
    protein: 36,
    category: "Sandwich",
    restaurant: "Subway",
  },
  {
    name: 'Turkey Breast 6"',
    calories: 280,
    protein: 18,
    category: "Sandwich",
    restaurant: "Subway",
  },
  {
    name: "Pepperoni Pizza (Large slice)",
    calories: 320,
    protein: 14,
    category: "Pizza",
    restaurant: "Domino's",
  },
  {
    name: "Cheesy Bread",
    calories: 140,
    protein: 6,
    category: "Sides",
    restaurant: "Domino's",
  },
  {
    name: "Pepperoni Pizza (slice)",
    calories: 300,
    protein: 13,
    category: "Pizza",
    restaurant: "Pizza Hut",
  },
  {
    name: "Meat Lovers Pizza (slice)",
    calories: 380,
    protein: 17,
    category: "Pizza",
    restaurant: "Pizza Hut",
  },
  {
    name: "Orange Chicken",
    calories: 490,
    protein: 25,
    category: "Entree",
    restaurant: "Panda Express",
  },
  {
    name: "Beijing Beef",
    calories: 470,
    protein: 13,
    category: "Entree",
    restaurant: "Panda Express",
  },
  {
    name: "Fried Rice",
    calories: 520,
    protein: 11,
    category: "Sides",
    restaurant: "Panda Express",
  },
  {
    name: "Double-Double",
    calories: 670,
    protein: 37,
    category: "Burger",
    restaurant: "In-N-Out",
  },
  {
    name: "Animal Style Fries",
    calories: 750,
    protein: 18,
    category: "Sides",
    restaurant: "In-N-Out",
  },
  {
    name: "Burrito Supreme",
    calories: 390,
    protein: 15,
    category: "Burrito",
    restaurant: "Taco Bell",
  },
  {
    name: "Egg McMuffin",
    calories: 310,
    protein: 17,
    category: "Breakfast",
    restaurant: "McDonald's",
  },
  {
    name: "Grilled Chicken Sandwich",
    calories: 380,
    protein: 37,
    category: "Sandwich",
    restaurant: "McDonald's",
  },
  {
    name: "Cinnamon Twists",
    calories: 170,
    protein: 2,
    category: "Dessert",
    restaurant: "Taco Bell",
  },
  {
    name: "Quesarito",
    calories: 650,
    protein: 22,
    category: "Burrito",
    restaurant: "Taco Bell",
  },
  {
    name: "Chicken Caesar Salad",
    calories: 470,
    protein: 40,
    category: "Salad",
    restaurant: "Chipotle",
  },
  {
    name: "Cookies (3 pack)",
    calories: 210,
    protein: 2,
    category: "Dessert",
    restaurant: "Subway",
  },
  {
    name: "Honey Mustard BBQ Tender Wrap",
    calories: 350,
    protein: 14,
    category: "Wrap",
    restaurant: "KFC",
  },
  {
    name: "McChicken Meal (with Med Fries)",
    calories: 720,
    protein: 19,
    category: "Combo",
    restaurant: "McDonald's",
  },
  {
    name: "Filet-O-Fish",
    calories: 390,
    protein: 16,
    category: "Sandwich",
    restaurant: "McDonald's",
  },
  {
    name: "Sausage McMuffin with Egg Meal",
    calories: 800,
    protein: 22,
    category: "Combo",
    restaurant: "McDonald's",
  },
  {
    name: "Double Quarter Pounder with Cheese",
    calories: 740,
    protein: 48,
    category: "Burger",
    restaurant: "McDonald's",
  },
  {
    name: "Whopper Meal (with Med Fries)",
    calories: 1040,
    protein: 33,
    category: "Combo",
    restaurant: "Burger King",
  },
  {
    name: "Original Chicken Sandwich",
    calories: 660,
    protein: 26,
    category: "Sandwich",
    restaurant: "Burger King",
  },
  {
    name: "Double Whopper",
    calories: 900,
    protein: 48,
    category: "Burger",
    restaurant: "Burger King",
  },
  {
    name: "Bacon King",
    calories: 1150,
    protein: 61,
    category: "Burger",
    restaurant: "Burger King",
  },
  {
    name: "Crunchwrap Supreme Combo",
    calories: 920,
    protein: 21,
    category: "Combo",
    restaurant: "Taco Bell",
  },
  {
    name: "3 Crunchy Tacos Combo",
    calories: 510,
    protein: 24,
    category: "Combo",
    restaurant: "Taco Bell",
  },
  {
    name: "Quesadilla (Chicken)",
    calories: 510,
    protein: 26,
    category: "Quesadilla",
    restaurant: "Taco Bell",
  },
  {
    name: "Cheesy Gordita Crunch",
    calories: 490,
    protein: 20,
    category: "Taco",
    restaurant: "Taco Bell",
  },
  {
    name: "Steak Burrito Bowl Combo",
    calories: 1100,
    protein: 52,
    category: "Combo",
    restaurant: "Chipotle",
  },
  {
    name: "Carnitas Burrito",
    calories: 850,
    protein: 42,
    category: "Burrito",
    restaurant: "Chipotle",
  },
  {
    name: "Barbacoa Tacos (3 pc)",
    calories: 540,
    protein: 34,
    category: "Taco",
    restaurant: "Chipotle",
  },
  {
    name: "3 pc Chicken Box (with Fries & Biscuit)",
    calories: 1010,
    protein: 51,
    category: "Combo",
    restaurant: "KFC",
  },
  {
    name: "Zinger Burger",
    calories: 540,
    protein: 30,
    category: "Sandwich",
    restaurant: "KFC",
  },
  {
    name: "Popcorn Chicken Combo",
    calories: 940,
    protein: 33,
    category: "Combo",
    restaurant: "KFC",
  },
  {
    name: "Twister Wrap",
    calories: 550,
    protein: 23,
    category: "Wrap",
    restaurant: "KFC",
  },
  {
    name: "Spicy Chicken Sandwich Combo",
    calories: 870,
    protein: 33,
    category: "Combo",
    restaurant: "Chick-fil-A",
  },
  {
    name: "8 pc Nuggets Combo",
    calories: 670,
    protein: 33,
    category: "Combo",
    restaurant: "Chick-fil-A",
  },
  {
    name: "Cobb Salad with Grilled Chicken",
    calories: 420,
    protein: 40,
    category: "Salad",
    restaurant: "Chick-fil-A",
  },
  {
    name: "3 pc Chicken Tenders Combo",
    calories: 890,
    protein: 38,
    category: "Combo",
    restaurant: "Popeyes",
  },
  {
    name: "Baconator Combo (with Med Fries)",
    calories: 1370,
    protein: 62,
    category: "Combo",
    restaurant: "Wendy's",
  },
  {
    name: "Dave's Single Combo",
    calories: 990,
    protein: 34,
    category: "Combo",
    restaurant: "Wendy's",
  },
  {
    name: "Spicy Chicken Sandwich",
    calories: 500,
    protein: 28,
    category: "Sandwich",
    restaurant: "Wendy's",
  },
  {
    name: "10 pc Chicken Nuggets",
    calories: 420,
    protein: 20,
    category: "Chicken",
    restaurant: "Wendy's",
  },
  {
    name: "Sweet Onion Chicken Teriyaki Footlong",
    calories: 740,
    protein: 50,
    category: "Sandwich",
    restaurant: "Subway",
  },
  {
    name: "Steak & Cheese Footlong",
    calories: 760,
    protein: 52,
    category: "Sandwich",
    restaurant: "Subway",
  },
  {
    name: "Meatball Marinara 6\"",
    calories: 430,
    protein: 20,
    category: "Sandwich",
    restaurant: "Subway",
  },
  {
    name: "ExtravaganZZa Pizza (Large slice)",
    calories: 380,
    protein: 16,
    category: "Pizza",
    restaurant: "Domino's",
  },
  {
    name: "Classic Chicken Alfredo Pasta",
    calories: 660,
    protein: 29,
    category: "Entree",
    restaurant: "Domino's",
  },
  {
    name: "Stuffed Crust Pepperoni Pizza (slice)",
    calories: 410,
    protein: 19,
    category: "Pizza",
    restaurant: "Pizza Hut",
  },
  {
    name: "Bigger Plate (2 Entrees + 1 Side)",
    calories: 1250,
    protein: 48,
    category: "Combo",
    restaurant: "Panda Express",
  },
  {
    name: "Mushroom Chicken",
    calories: 220,
    protein: 13,
    category: "Entree",
    restaurant: "Panda Express",
  },
  {
    name: "Broccoli Beef",
    calories: 150,
    protein: 9,
    category: "Entree",
    restaurant: "Panda Express",
  },
  {
    name: "Double-Double Combo (with Fries)",
    calories: 1060,
    protein: 42,
    category: "Combo",
    restaurant: "In-N-Out",
  },
  {
    name: "Hamburger",
    calories: 390,
    protein: 16,
    category: "Burger",
    restaurant: "In-N-Out",
  },
  {
    name: "Beltsander Wrap",
    calories: 520,
    protein: 26,
    category: "Wrap",
    restaurant: "Tim Hortons",
  },
  {
    name: "Chili with Toast",
    calories: 430,
    protein: 19,
    category: "Entree",
    restaurant: "Tim Hortons",
  },
  {
    name: "Iced Capp (Medium)",
    calories: 360,
    protein: 3,
    category: "Drink",
    restaurant: "Tim Hortons",
  },
  {
    name: "Mozza Burger",
    calories: 560,
    protein: 29,
    category: "Burger",
    restaurant: "A&W",
  },
  {
    name: "Papa Burger Combo (with Fries)",
    calories: 1020,
    protein: 35,
    category: "Combo",
    restaurant: "A&W",
  },
  {
    name: "Sweet Potato Fries",
    calories: 380,
    protein: 3,
    category: "Sides",
    restaurant: "A&W",
  },
  {
    name: "ShackBurger",
    calories: 530,
    protein: 30,
    category: "Burger",
    restaurant: "Shake Shack",
  },
  {
    name: "SmokeShack Double",
    calories: 870,
    protein: 53,
    category: "Burger",
    restaurant: "Shake Shack",
  },
  {
    name: "Cheese Fries",
    calories: 560,
    protein: 12,
    category: "Sides",
    restaurant: "Shake Shack",
  },
  {
    name: "Little Bacon Cheeseburger",
    calories: 730,
    protein: 32,
    category: "Burger",
    restaurant: "Five Guys",
  },
  {
    name: "Fries (Little size)",
    calories: 530,
    protein: 8,
    category: "Sides",
    restaurant: "Five Guys",
  },
  {
    name: "Classic Beef Patty",
    calories: 340,
    protein: 11,
    category: "Bakery",
    restaurant: "Dairy Queen",
  },
];

export function pickRandomFood(): Food {
  return foods[Math.floor(Math.random() * foods.length)];
}

export function pickDailyFood(): Food {
  // Get today's date as YYYY-MM-DD
  const today = new Date().toISOString().split("T")[0];
  // Convert date string to a number for seeding
  const seed = today.split("-").reduce((acc, part) => acc + parseInt(part), 0);
  // Use modulo to get a consistent index for today
  const index = seed % foods.length;
  return foods[index];
}
